FROM golang:alpine as builder

RUN apk update && apk add git && apk add ca-certificates

RUN adduser -D -g '' appuser 

COPY . $GOPATH/src/github.com/linkai-io/frontend/
WORKDIR $GOPATH/src/github.com/linkai-io/frontend/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags '-w -s' -o /go/bin/supportprovision cmd/supportprovision/main.go

# STEP 2 build a small image
# start from scratch
FROM scratch
# Copy our static executable and supporting
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /go/bin/supportprovision /go/bin/supportprovision 
USER appuser 

ENTRYPOINT ["/go/bin/supportprovision"]